config/routes.rb
Rails.application.routes.draw do
  root to: "decks#index"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  get "/cards/report", to: "cards#report"
  resources :cards do
    member do
      patch :move_decks
      delete :delete_audio_sample
    end
  end

  resources :decks do
    member do
      patch :next_card, as: :next_card_in
      patch :previous_card, as: :previous_card_in
      patch :take_cards
      patch :shuffle
      get :sort_cards
      get :study
    end
  end

  resources :card_decks, only: [:create, :destroy] do
    collection do
      patch :sort
    end
  end

  %w( 404 422 500 503 ).each do |code|
    get code, to: "static_pages#error", code: code
  end
end

app/models/card.rb
class Card < ApplicationRecord
  DIFFICULTIES = (1..5).to_a.freeze

  has_many :card_decks, dependent: :destroy
  has_many :decks, through: :card_decks
  has_one_attached :audio_sample

  validates :english, presence: true
  validates :kana, presence: true
  validates :difficulty, inclusion: { in: DIFFICULTIES }

  before_save :trim_text_values

  private

  def trim_text_values
    self.english = self.english&.strip
    self.kana = self.kana&.strip
    self.kanji = self.kanji&.strip
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, except: [:index, :new, :create, :report]

  def index
    @cards = Card.includes(:card_decks).order(english: :asc)
  end

  def show
  end

  def new
    @card = Card.new
    @decks = Deck.order(created_at: :asc)
  end

  def edit
    @decks = Deck.order(created_at: :asc)
  end

  def create
    ActiveRecord::Base.transaction do
      @card = Card.create!(card_params)
      if params[:card][:deck_id].present?
        CardDeck.create!(card: @card, deck_id: params[:card][:deck_id])
      end
    end
    redirect_to card_path(@card)
  rescue ActiveRecord::RecordNotUnique
    flash[:alert] = "A card already exists for: '#{card_params[:english]}'"
    redirect_to new_card_path
  end

  def update
    # If we are updating the difficulty, the cards_to_study query may lose it's
    # place in the deck. We need to check if the new difficulty falls within the
    # decks's difficulty range, and if so move the current card marker back to
    # the last card still in range before updating this card.
    if card_params[:difficulty]
      CardDeck.where(card: @card, status: CardDeck::CURRENT_CARD).each do |card_deck|
        deck = card_deck.deck
        unless (deck.minimum_difficulty..deck.maximum_difficulty).include?(card_params[:difficulty].to_i)
          deck.previous_card
        end
      end
    end

    @card.update(card_params)
    respond_to do |format|
      format.json { head :ok }
      format.html { redirect_to card_path(@card) }
    end
  end

  def destroy
    @card.destroy
    respond_to(&:js)
  end

  def delete_audio_sample
    @card.audio_sample.purge
    redirect_to edit_card_path(@card)
  end

  def report
    @total_cards = Card.count
    @total_card_views = Card.sum(:review_count).to_i
    @cards_not_in_decks = Card.left_outer_joins(:card_decks).where(card_decks: { card_id: nil })
  end

  private

  def card_params
    params.require(:card).permit(:english, :kana, :kanji, :audio_sample, :difficulty)
  end

  def set_card
    @card = Card.includes(card_decks: [:card]).find(params[:id])
  end
end

app/views/cards/_card.html.erb
<tr data-card-id="<%= card.id %>">
  <td><%= link_to(card.english, card_path(card), class: "has-text-link") %></td>
  <td class="edit-card-cell"><%= card.card_decks.size %></td>
  <td class="edit-card-cell">
    <%= link_to(edit_card_path(card), class: "has-text-link") do %>
      <span class="icon is-small">
        <i class="fas fa-edit"></i>
      </span>
    <% end %>
  </td>
  <td class="edit-card-cell">
    <%= link_to(card_path(card), class: "has-text-link", data: { confirm: "Are you sure you want to delete this card? This action is permanent and cannot be undone." }, method: :delete, remote: true ) do %>
      <span class="icon is-small">
        <i class="fas fa-trash"></i>
      </span>
    <% end %>
  </td>
</tr>

app/views/cards/_editable_card.html.erb
<tr>
  <td><%= link_to(card.english, card_path(card), class: "has-text-link") %></td>
  <td class="edit-card-cell">
    <%= link_to(edit_card_path(card), class: "has-text-link") do %>
      <span class="icon is-small">
        <i class="fas fa-edit"></i>
      </span>
    <% end %>
  </td>
  <td class="edit-card-cell">
    <%= link_to(card_path(card), class: "has-text-link", data: { confirm: "Are you sure you want to delete this card? This action is permanent and cannot be undone." }, method: :delete, remote: true ) do %>
      <span class="icon is-small">
        <i class="fas fa-trash"></i>
      </span>
    <% end %>
  </td>
</tr>

app/views/cards/_sortable_card.html.erb
<tr data-card-id="<%= card.id %>" data-deck-id="<%= @deck.id %>">
  <td><%= link_to(card.english, card_path(card), class: "has-text-link") %></td>
</tr>

app/views/cards/destroy.js.erb
var deletedCard = document.querySelector('[data-card-id="<%= @card.id %>"]');
deletedCard.parentElement.removeChild(deletedCard);

app/views/cards/edit.html.erb
<div class="edit-resource">
  <div class="edit-resource-form-container" data-controller="card form">
    <h2 class="title is-4">Edit card</h2>

    <%= form_with(model: @card, url: card_path(@card), local: true) do |f| %>
      <div class="field">
        <%= f.label :english %>
        <%= f.text_field :english, autocomplete: 'off', class: "input" %>
      </div>

      <div class="field">
        <%= f.label :kana %>
        <%= f.text_field :kana, autocomplete: 'off', class: "input" %>
      </div>

      <div class="field">
        <%= f.label :kanji %>
        <%= f.text_field :kanji, autocomplete: 'off', class: "input" %>
      </div>

      <% if @card.audio_sample.attached? %>
        <div class="current-audio-sample">
          <p>Current audio sample</p>
          <%= render(template: 'decks/_play_audio_sample_button', locals: { current_card: @card }) %>
          <%= link_to(delete_audio_sample_card_path(@card), class: "has-text-danger delete-audio-sample-button", data: { confirm: "Are you sure you want to delete this audio sample? This action is permanent and cannot be undone." }, method: :delete, remote: true ) do %>
            <span class="icon is-small">
              <i class="fas fa-trash"></i>
            </span>
          <% end %>
        </div>
      <% end %>

      <div class="field audio-sample-upload">
        <div class="file is-small">
          <label class="file-label">
            <%= f.file_field :audio_sample, class: "file-input", data: { target: "form.fileInput", action: "change->form#showFileName" } %>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fas fa-upload"></i>
              </span>
              <span class="file-label">Upload a new audio sample...</span>
            </span>
            <span class="file-name" data-form-target="fileName"></span>
          </label>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Update", class: "button is-info" %>
        <%= link_to "Back", :back, class: "button is-info is-outlined" %>
      </div>
    <% end %>
  </div>

  <div class="decks-list">
    <h2 class="title is-4">Manage card decks</h2>
    <table class="table is-fullwidth is-hoverable is-striped">
      <thead>
        <tr>
          <th class="included-in-deck-column">Included</th>
          <th>Name</th>
          <th class="edit-column">Edit</th>
          <th class="edit-column">Delete</th>
        </tr>
      </thead>
      <tbody>
        <%= render(partial: 'decks/addable_deck', collection: @decks, as: :deck, locals: { card: @card }) %>
      </tbody>
    </table>
  </div>
</div>

app/views/cards/index.html.erb
<div class="all-cards-container">
  <div class="all-cards-card">
    <table class="table is-fullwidth is-hoverable is-striped">
      <thead>
        <tr>
          <th>English</th>
          <th class="edit-column">
            <span class="large-header">Decks</span>
            <span class="icon is-small small-header">
              <i class="fas fa-layer-group"></i>
            </span>
          </th>
          <th class="edit-column">
            <span class="large-header">Edit</span>
            <span class="icon is-small small-header">
              <i class="fas fa-edit"></i>
            </span>
          </th>
          <th class="edit-column">
            <span class="large-header">Delete</span>
            <span class="icon is-small small-header">
              <i class="fas fa-trash"></i>
            </span>
          </th>
        </tr>
      </thead>
      <tbody>
        <%= render(partial: 'cards/card', collection: @cards, cached: true) %>
      </tbody>
    </table>
  </div>
</div>

app/views/cards/new.html.erb
<div class="new-resource">
  <div class="new-resource-form-container" data-controller="form">
    <h2 class="title is-4">New card</h2>

    <%= form_with(model: @card, url: cards_path) do |f| %>
      <div class="field">
        <%= f.label :english %>
        <%= f.text_field :english, autocomplete: 'off', class: "input" %>
      </div>

      <div class="field">
        <%= f.label :kana %>
        <%= f.text_field :kana, autocomplete: 'off', class: "input" %>
      </div>

      <div class="field">
        <%= f.label :kanji %>
        <%= f.text_field :kanji, autocomplete: 'off', class: "input" %>
      </div>

      <div class="field audio-sample-upload">
        <div class="file is-small has-name">
          <label class="file-label">
            <%= f.file_field :audio_sample, class: "file-input", data: { target: "form.fileInput", action: "change->form#showFileName" } %>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fas fa-upload"></i>
              </span>
              <span class="file-label">Upload audio sample...</span>
            </span>
            <span class="file-name" data-form-target="fileName"></span>
          </label>
        </div>
      </div>

      <div class="field">
        <%= f.label "Create in deck" %><br/>
        <div class="select is-small">
          <%= f.select :deck_id, options_from_collection_for_select(@decks, "id", "name") %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Create", class: "button is-info" %>
        <%= link_to "Back", :back, class: "button is-info is-outlined" %>
      </div>
    <% end %>
  </div>
</div>

app/views/cards/report.html.erb
<div class="cards-report">
  <div class="cards-report-container">
    <h2 class="title is-4">Cards report</h2>
    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th>Metric</th>
          <th>Sum</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Cards</td>
          <td><%= @total_cards %></td>
        </tr>
        <tr>
          <td>Card views</td>
          <td><%= @total_card_views %></p></td>
        </tr>
        <tr>
          <td>Cards not in decks</td>
          <td><%= @cards_not_in_decks.size %></td>
        </tr>
    </table>

    <% if @cards_not_in_decks.size > 0 %>
      <div class="cards-not-in-decks">
        <h2 class="title is-4">Cards not in decks</h2>
        <table class="table is-fullwidth is-hoverable is-striped cards-list">
          <thead>
            <tr>
              <th>English</th>
              <th class="edit-column">
                <span class="large-header">Edit</span>
                <span class="icon is-small small-header">
                  <i class="fas fa-edit"></i>
                </span>
              </th>
              <th class="edit-column">
                <span class="large-header">Delete</span>
                <span class="icon is-small small-header">
                  <i class="fas fa-trash"></i>
                </span>
              </th>
            </tr>
          </thead>
          <tbody>
            <%= render(partial: 'cards/editable_card', collection: @cards_not_in_decks, as: :card, cached: true) %>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>

app/views/cards/show.html.erb
<div class="card-details-container" data-controller="card">
  <div class="card-details-card">
    <div class="english-text"><%= @card.english %></div>
    <div class="kana-text"><%= @card.kana %></div>
    <div class="kanji-text"><%= @card.kanji %></div>
    <div class="audio-sample">
      <% if @card.audio_sample.attached? %>
        <%= render(template: 'decks/_play_audio_sample_button', locals: { current_card: @card }) %>
      <% end %>
    </div>
    <%= link_to(edit_card_path(@card), class: "has-text-grey-lighter card-edit-button") do %>
      <span class="icon is-small">
        <i class="fas fa-edit"></i>
      </span>
    <% end %>
  </div>
</div>