config/routes.rb
Rails.application.routes.draw do
  root to: "decks#index"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  get "/cards/report", to: "cards#report"
  resources :cards do
    member do
      patch :move_decks
      delete :delete_audio_sample
    end
  end

  resources :decks do
    member do
      patch :next_card, as: :next_card_in
      patch :previous_card, as: :previous_card_in
      patch :take_cards
      patch :shuffle
      get :sort_cards
      get :study
    end
  end

  resources :card_decks, only: [:create, :destroy] do
    collection do
      patch :sort
    end
  end

  %w( 404 422 500 503 ).each do |code|
    get code, to: "static_pages#error", code: code
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :card_decks, dependent: :destroy
  has_many :cards, through: :card_decks

  validates :name, presence: true
  validates :maximum_difficulty, inclusion: { in: Card::DIFFICULTIES }
  validates :minimum_difficulty, inclusion: { in: Card::DIFFICULTIES }
  validate :start_with_valid

  VALID_START_WITH_VALUES = ["kana", "kanji", "english", "audio_sample"].freeze

  def shuffle
    # This method suspends the auto-sorting callbacks while I manually change
    # position values. Without this card_deck positions end up with duplicates
    # or gaps, breaking the ordered deck functionality.
    CardDeck.acts_as_list_no_update do
      new_positions = (1..card_decks.size).to_a.shuffle
      card_decks.map { |card_deck| card_deck.update(position: new_positions.pop) }
    end
    CardDeck.where(deck: self, status: CardDeck::CURRENT_CARD).update(status: nil)
    self
  end

  def cards_to_study(shuffled = false)
    if shuffled
      # Reset cache if deck was just shuffled
      @cards_to_study = cards.where(difficulty: minimum_difficulty..maximum_difficulty)
    end
    @cards_to_study ||= cards.where(difficulty: minimum_difficulty..maximum_difficulty)
  end

  def current_card
    Card.joins(card_decks: [:deck]).where(
      card_decks: { deck_id: id, status: CardDeck::CURRENT_CARD },
      difficulty: minimum_difficulty..maximum_difficulty
    ).first || begin
      current_card = cards_to_study.first
      CardDeck.where(deck: self, status: CardDeck::CURRENT_CARD).update(status: nil)
      CardDeck.find_by(deck: self, card: current_card)&.update(status: CardDeck::CURRENT_CARD)
      current_card
    end
  end

  def next_card
    Deck.transaction(requires_new: true) do
      index = cards_to_study.index { |c| c.id == current_card.id }
      return unless index.present?
      next_card = cards_to_study[index + 1] || begin
        is_randomized ? shuffle.reload.cards_to_study(true)[0] : cards_to_study[0]
      end
      CardDeck.where(deck: self, status: CardDeck::CURRENT_CARD).update(status: nil)
      CardDeck.find_by(deck: self, card: next_card).update(status: CardDeck::CURRENT_CARD)
      next_card
    end
  end

  def previous_card
    Deck.transaction(requires_new: true) do
      index = cards_to_study.index { |c| c.id == current_card.id }
      return unless index.present?
      previous_card = cards_to_study[index - 1]
      CardDeck.where(deck: self, status: CardDeck::CURRENT_CARD).update(status: nil)
      CardDeck.find_by(deck: self, card: previous_card).update(status: CardDeck::CURRENT_CARD)
      previous_card
    end
  end

  def progress
    current_card_position = cards_to_study.index { |c| c.id == current_card.id }
    return unless current_card_position
    "#{current_card_position + 1} / #{cards_to_study.size}"
  end

  private

  def start_with_valid
    unless VALID_START_WITH_VALUES.include?(start_with)
      errors.add(:start_with, "not included in '#{VALID_START_WITH_VALUES}'")
    end
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, except: [:index, :new, :create]

  def index
    @decks = Deck.includes(:card_decks).order(created_at: :asc)
  end

  def show
  end

  def new
    @deck = Deck.new
    @start_with_options = start_with_options(@deck)
  end

  def edit
    @start_with_options = start_with_options(@deck)
    @availible_decks = Deck.order(created_at: :asc).where.not(id: @deck.id)
  end

  def sort_cards
  end

  def create
    @deck = Deck.create!(deck_params)
    flash[:success] = "#{@deck.name} was successfully created!"
    redirect_to decks_path
  end

  def update
    @deck.update(deck_params)
    respond_to do |format|
      format.json { head :ok }
      format.html { redirect_to decks_path }
    end
  end

  def destroy
    @deck.destroy
    respond_to(&:js)
  end

  def take_cards
    if invalid_take_cards_info?
      flash[:notice] = "Specify the number of cards to move, target deck and difficulty"
      return redirect_to edit_deck_path(@deck)
    end

    if params[:take_from_deck_id].present?
      take_from_deck = Deck.includes(:card_decks).find(params[:take_from_deck_id])
      move_to_deck = @deck
    elsif params[:move_to_deck_id].present?
      take_from_deck = @deck
      move_to_deck = Deck.find(params[:move_to_deck_id])
    end

    cards_to_take = take_from_deck.cards
      .where(difficulty: params[:minimum_difficulty].to_i..params[:maximum_difficulty].to_i)
      .take(params[:number_of_cards].to_i)
    ActiveRecord::Base.transaction(joinable: false) do
      cards_to_take.each { |card| CardDeck.find_by(deck: take_from_deck, card: card).move_to(new_deck: move_to_deck) }
    end

    flash[:success] = "#{cards_to_take.size} #{"card".pluralize(cards_to_take.size)} moved to #{move_to_deck.name}"
    redirect_to decks_path
  end

  def next_card
    next_card = @deck.next_card
    unless next_card
      show_no_matching_cards_message
      return redirect_to deck_path(@deck)
    end
    next_card.increment!(:review_count, touch: true)
    respond_to do |format|
      format.html { redirect_to deck_path(@deck) }
      format.js {
        @current_card = next_card
        @progress = @deck.progress
      }
    end
  end

  def previous_card
    previous_card = @deck.previous_card
    unless previous_card
      show_no_matching_cards_message
      return redirect_to deck_path(@deck)
    end
    previous_card.increment!(:review_count, touch: true)
    respond_to do |format|
      format.html { redirect_to deck_path(@deck) }
      format.js {
        @current_card = previous_card
        @progress = @deck.progress
        render '/decks/next_card'
      }
    end
  end

  def shuffle
    @deck.shuffle
    flash[:success] = "Deck shuffled!"
    redirect_to deck_path(@deck)
  end

  def study
    @current_card = @deck.current_card
    unless @current_card
      show_no_matching_cards_message
      return redirect_to deck_path(@deck)
    end

    @current_card.increment!(:review_count, touch: true)
    @progress = @deck.progress
  end

  private

  def deck_params
    params.require(:deck).permit(:name, :start_with, :is_randomized, :maximum_difficulty, :minimum_difficulty)
  end

  def set_deck
    @deck = Deck.includes(card_decks: [:card]).find(params[:id])
  end

  def start_with_options(deck)
    valid_values = Deck::VALID_START_WITH_VALUES

    unless deck.cards&.all? { |card| card.audio_sample.attached? }
      valid_values = valid_values - Array("audio_sample")
    end

    unless deck.cards&.all? { |card| card.kanji.present? }
      valid_values = valid_values - Array("kanji")
    end

    valid_values.map do |start_with_value|
      [start_with_value.titleize, start_with_value]
    end
  end

  def invalid_take_cards_info?
    (params[:take_from_deck_id].blank? && params[:move_to_deck_id].blank?) || (params[:take_from_deck_id].present? && params[:move_to_deck_id].present?) || params[:number_of_cards].to_i.zero?
  end

  def show_no_matching_cards_message
    if @deck.maximum_difficulty < @deck.minimum_difficulty
      flash[:alert] = "Deck maximum cannot be set lower than deck minimum"
    else
      flash[:notice] = "No cards in this deck have a difficulty between maximum: #{@deck.maximum_difficulty} and minimum: #{@deck.minimum_difficulty}"
    end
  end
end

app/views/decks/_addable_deck.html.erb
<tr class="deck-id-<%= deck.id %>" data-controller="card-deck">
  <% if @card.present? %>
    <td class="included-in-deck-cell">
      <% @card_deck = @card.card_decks.detect { |cg| cg.deck_id == deck.id } %>
      <% if @card_deck.present? %>
        <%= form_with(model: @card_deck, url: card_deck_path(@card_deck), method: "delete", data: { target: "card-deck.form" }) do |f| %>
          <%= f.check_box :included, data: { action: "change->card-deck#toggle" }, checked: true %>
        <% end %>
      <% else %>
        <%= form_with(model: CardDeck.new, url: card_decks_path, method: "post", data: { target: "card-deck.form"}) do |f| %>
          <%= f.check_box :included, data: { action: "change->card-deck#toggle" }, checked: false %>
          <%= f.hidden_field :card_id, value: @card.id %>
          <%= f.hidden_field :deck_id, value: deck.id %>
        <% end %>
      <% end %>
    </td>
  <% end %>
  <td><%= link_to(deck.name, deck_path(deck), class: "has-text-link") %></td>
  <td class="edit-deck-cell">
    <%= link_to(edit_deck_path(deck), class: "has-text-link") do %>
      <span class="icon is-small">
        <i class="fas fa-edit"></i>
      </span>
    <% end %>
  </td>
  <td class="edit-deck-cell">
    <%= link_to(deck_path(deck), class: "has-text-link", data: { confirm: "Are you sure you want to delete this deck? This action is permanent and cannot be undone." }, method: :delete, remote: true ) do %>
      <span class="icon is-small">
        <i class="fas fa-trash"></i>
      </span>
    <% end %>
  </td>
</tr>

app/views/decks/_deck.html.erb
<tr class="deck-id-<%= deck.id %>" data-controller="card-deck">
  <td><%= link_to(deck.name, deck_path(deck), class: "has-text-link") %></td>
  <td class="edit-deck-cell">
    <%= deck.card_decks.size %>
  </td>
  <td class="edit-deck-cell">
    <%= link_to(edit_deck_path(deck), class: "has-text-link") do %>
      <span class="icon is-small">
        <i class="fas fa-edit"></i>
      </span>
    <% end %>
  </td>
  <td class="edit-deck-cell">
    <%= link_to(deck_path(deck), class: "has-text-link", data: { confirm: "Are you sure you want to delete this deck? This action is permanent and cannot be undone." }, method: :delete, remote: true ) do %>
      <span class="icon is-small">
        <i class="fas fa-trash"></i>
      </span>
    <% end %>
  </td>
</tr>

app/views/decks/_play_audio_sample_button.html.erb
<a
  href="<%= url_for(current_card.audio_sample) %>"
  class="button is-outlined play-audio-sample-button"
  data-action="click->card#playAudio"
  data-card-target="playAudioSampleButton"
>
  <span class="icon">
    <i class="fas fa-lg fa-volume-up"></i>
  </span>
</a>

app/views/decks/destroy.js.erb
var deletedDeck = document.querySelector(".deck-id-<%= @deck.id %>");
deletedDeck.parentElement.removeChild(deletedDeck);

app/views/decks/edit.html.erb
<div class="edit-resource">
  <div class="edit-resource-form-container">
    <h2 class="title is-4">Edit deck</h2>

    <%= form_with(model: @deck, url: deck_path(@deck), class: "edit-deck-form", local: true) do |f| %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, autocomplete: 'off', class: "input" %>
      </div>

      <div class="field">
        <%= f.label "Front of card shows" %><br/>
        <div class="select is-small">
          <%= f.select :start_with, options_for_select(@start_with_options, @deck.start_with) %>
        </div>
      </div>

      <div class="field">
        <label class="checkbox">
          <%= f.check_box :is_randomized, class: "randomized-checkbox" %>
          Shuffle after each complete review
        </label>
      </div>

      <div class="actions">
        <%= f.submit "Update", class: "button is-info" %>
        <%= link_to "Back", :back, class: "button is-info is-outlined" %>
      </div>
    <% end %>
  </div>

  <div class="more-deck-actions">
    <h2 class="title is-4">Manage cards</h2>
    <p class="has-text-grey-light current-card-count">
      (<%= @deck.card_decks.size %> cards currently in this deck)
    </p>
    <%= form_tag(take_cards_deck_path(@deck), method: :patch, class: "next-card-form") do %>
      <div class="field">
        <label>Number of cards</label>
        <input name="number_of_cards" type="text" class="input" autocomplete="off" />
      </div>
      <div class="select is-small">
        <%= select_tag :take_from_deck_id, options_from_collection_for_select(@availible_decks, "id", "name"), prompt: "Take from deck..." %>
      </div>
      <div class="select is-small">
        <%= select_tag :move_to_deck_id, options_from_collection_for_select(@availible_decks, "id", "name"), prompt: "Move to deck..." %>
      </div>
      <div class="select is-small">
        <%= select_tag :maximum_difficulty, options_for_select(Card::DIFFICULTIES), prompt: "Max difficulty..." %>
      </div>
      <div class="select is-small">
        <%= select_tag :minimum_difficulty, options_for_select(Card::DIFFICULTIES), prompt: "Min difficulty..." %>
      </div>

      <br/><br/>
      <%= submit_tag "Move cards", data: { confirm: "Are you sure you want move cards between decks? This action is permanent and cannot be undone." }, class: "button is-info" %>
      <%= link_to("Sort cards", sort_cards_deck_path(@deck), class: "button is-info is-outlined sort-cards-button") %>
    <% end %>
  </div>
</div>

app/views/decks/index.html.erb
<div class="all-decks-container">
  <div class="all-decks-card">
    <table class="table is-fullwidth is-hoverable is-striped">
      <thead>
        <tr>
          <th>Deck Name</th>
          <th class="edit-column">
            <span class="large-header">Cards</span>
            <span class="icon is-small small-header">
              <i class="fas fa-sticky-note"></i>
            </span>
          </th>
          <th class="edit-column">
            <span class="large-header">Edit</span>
            <span class="icon is-small small-header">
              <i class="fas fa-edit"></i>
            </span>
          </th>
          <th class="edit-column">
            <span class="large-header">Delete</span>
            <span class="icon is-small small-header">
              <i class="fas fa-trash"></i>
            </span>
          </th>
        </tr>
      </thead>
      <tbody>
        <%= render(partial: 'decks/deck', collection: @decks, cached: true) %>
      </tbody>
    </table>
  </div>
</div>

app/views/decks/new.html.erb
<div class="new-resource">
  <div class="new-resource-form-container">
    <h2 class="title is-4">New deck</h2>

    <%= form_with(model: @deck, url: decks_path) do |f| %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, autocomplete: 'off', class: "input" %>
      </div>

      <div class="field">
        <%= f.label "Front of card shows" %><br/>
        <div class="select is-small">
          <%= f.select :start_with, options_for_select(@start_with_options, @deck.start_with) %>
        </div>
      </div>

      <div class="field">
        <label class="checkbox">
          <%= f.check_box :is_randomized, class: "randomized-checkbox" %>
          Shuffle after each complete review
        </label>
      </div>

      <div class="actions">
        <%= f.submit "Create", class: "button is-info" %>
        <%= link_to "Back", :back, class: "button is-info is-outlined" %>
      </div>
    <% end %>
  </div>
</div>

app/views/decks/next_card.js.erb
(function() {
  var loader = document.querySelector('.loader-wrapper');
  var englishText = document.querySelector(".english-text");
  var kanaText = document.querySelector(".kana-text");
  var kanjiText = document.querySelector(".kanji-text");
  var audioSample = document.querySelector(".audio-sample");
  var deckProgressLabel = document.querySelector(".deck-progress small");
  var cardInteractionContainer = document.querySelector(".card-interaction-container");
  var editCardButton = document.querySelector(".card-edit-button");

  loader.classList.remove("is-active");
  englishText.innerHTML = "<%= @current_card.english %>";
  kanaText.innerHTML = "<%= @current_card.kana %>";
  kanjiText.innerHTML = "<%= @current_card.kanji %>";

  <% if @current_card.audio_sample.attached? %>
    audioSample.innerHTML = '<%= raw(render(template: "decks/_play_audio_sample_button", locals: { current_card: @current_card }).squish) %>';
    var playAudioSampleButton = document.querySelector(".play-audio-sample-button");
    playAudioSampleButton.audio = new Audio(playAudioSampleButton.href);
  <% end %>

  deckProgressLabel.innerHTML = "<%= @progress %>";
  editCardButton.href = "<%= edit_card_url(@current_card.id) %>";
  cardInteractionContainer.dataset.studyCardUpdateUrl = "<%= card_path(@current_card) %>";
}());

app/views/decks/show.html.erb
<div class="deck-show-container" data-controller="deck" data-deck-update-url="<%= deck_path(@deck) %>">
  <h1 class="title deck-name"><%= @deck.name %></h1>

  <div class="actions">
    <%= form_tag(shuffle_deck_path(@deck), method: :patch, class: "shuffle-deck-form") do %>
      <div class="actions">
        <%= submit_tag "Shuffle", data: { confirm: "Are you sure you want to shuffle this deck? This action is permanent and cannot be undone." }, class: "button is-info is-outlined" %>
      </div>
    <% end %>
    <%= link_to("Edit deck", edit_deck_path(@deck), class: "button is-info is-outlined") %>
  </div>

  <br/>
  <h2 class="specify-difficulty">Max difficulty</h2>
  <div class="difficulty-options">
    <% Card::DIFFICULTIES.each do |difficulty| %>
      <% if difficulty == @deck.maximum_difficulty %>
        <button class="button maximum-difficulty is-success" data-action="click->deck#selectMaximumDifficulty"><%= difficulty %></button>
      <% else %>
        <button class="button maximum-difficulty is-white" data-action="click->deck#selectMaximumDifficulty"><%= difficulty %></button>
      <% end %>
    <% end %>
  </div>

  <br/>
  <h2 class="specify-difficulty">Minimum difficulty</h2>
  <div class="difficulty-options">
    <% Card::DIFFICULTIES.each do |difficulty| %>
      <% if difficulty == @deck.minimum_difficulty %>
        <button class="button minimum-difficulty is-success" data-action="click->deck#selectMinimumDifficulty"><%= difficulty %></button>
      <% else %>
        <button class="button minimum-difficulty is-white" data-action="click->deck#selectMinimumDifficulty"><%= difficulty %></button>
      <% end %>
    <% end %>
  </div>

  <br/>
  <%= link_to("Study now", study_deck_path(@deck), class: "button is-info", data: { target: "deck.studyNowButton" } ) %>
</div>

<form name="ignore_me">
    <input type="hidden" id="page_is_dirty" name="page_is_dirty" value="0" />
</form>

<script>
  var dirty_bit = document.getElementById('page_is_dirty');
  if (dirty_bit.value == '1') {
    window.location.reload();
  }
  dirty_bit.value = '1';
</script>

app/views/decks/sort_cards.html.erb
<div class="sort-cards">
  <div class="cards-list">
    <div class="header-container">
      <h2 class="title is-4">Re-order cards in deck</h2>
      <%= link_to("Back", :back, class: "back-button button is-info is-outlined is-small") %>
    </div>
    <table class="table is-fullwidth is-hoverable is-striped">
      <thead>
        <tr>
          <th>English</th>
        </tr>
      </thead>
      <tbody data-controller="sortable" data-sortable-url="/card_decks/sort">
        <%= render(partial: 'cards/sortable_card', collection: @deck.cards, as: :card, locals: { deck: @deck }) %>
      </tbody>
    </table>
  </div>
</div>

app/views/decks/study.html.erb
<div class="deck-study-container">
  <% if @current_card %>
    <div class="card-interaction-container" data-controller="card study" data-study-start-with="<%= @deck.start_with %>" data-study-card-update-url="<%= card_path(@current_card) %>">
      <div class="deck-card">
        <div class="flip-card-button-container" data-action="click->study#flipCard">
          <span class="flip-card-button has-text-grey-lighter">
            <small>Flip card</small>
          </span>
        </div>
        <span class="deck-progress has-text-grey-lighter"><small><%= @progress %></small></span>
        <span class="icon has-text-grey-lighter card-options-button" data-action="click->study#toggleCardOptions">
          <i class="fas fa-ellipsis-h"></i>
        </span>

        <div class="english-text" data-study-target="englishText"><%= @current_card.english %></div>
        <div class="kana-text" data-study-target="kanaText"><%= @current_card.kana %></div>
        <div class="kanji-text" data-study-target="kanjiText"><%= @current_card.kanji %></div>
        <div class="audio-sample" data-study-target="audioSample">
          <% if @current_card.audio_sample.attached? %>
            <%= render(template: 'decks/_play_audio_sample_button', locals: { current_card: @current_card }) %>
          <% end %>
        </div>

        <div class="loader-wrapper" data-study-target="loader">
          <div class="loader is-loading"></div>
        </div>

        <%= form_tag(previous_card_in_deck_path(@deck.id), method: :patch, class: "previous-card-form", remote: true) do %>
          <%= button_tag type: 'submit', class: "button is-white", data: { action: "click->study#prepareForNextCard" } do %>
            <span class="icon has-text-grey-lighter">
              <i class="fas fa-2x fa-caret-left"></i>
            </span>
          <% end %>
        <% end %>

        <%= form_tag(next_card_in_deck_path(@deck.id), method: :patch, class: "next-card-form", remote: true) do %>
          <%= button_tag type: 'submit', class: "button is-white", data: { action: "click->study#prepareForNextCard" } do %>
            <span class="icon has-text-grey-lighter">
              <i class="fas fa-2x fa-caret-right"></i>
            </span>
          <% end %>
        <% end %>

        <div class="card-options" data-study-target="cardOptions">
          <div class="card-difficulty-label has-text-grey">Rate card difficulty:</div>
          <button class="button is-light" data-action="click->study#setCardDifficulty">1</button>
          <button class="button is-light" data-action="click->study#setCardDifficulty">2</button>
          <button class="button is-light" data-action="click->study#setCardDifficulty">3</button>
          <button class="button is-light" data-action="click->study#setCardDifficulty">4</button>
          <button class="button is-light" data-action="click->study#setCardDifficulty">5</button>
        </div>

        <%= link_to(edit_card_path(@current_card), class: "has-text-grey-lighter card-edit-button", data: { target: "study.editCard" } ) do %>
          <span class="icon is-small">
            <i class="fas fa-edit"></i>
          </span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>