config/routes.rb
Rails.application.routes.draw do
  root to: "decks#index"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  get "/cards/report", to: "cards#report"
  resources :cards do
    member do
      patch :move_decks
      delete :delete_audio_sample
    end
  end

  resources :decks do
    member do
      patch :next_card, as: :next_card_in
      patch :previous_card, as: :previous_card_in
      patch :take_cards
      patch :shuffle
      get :sort_cards
      get :study
    end
  end

  resources :card_decks, only: [:create, :destroy] do
    collection do
      patch :sort
    end
  end

  %w( 404 422 500 503 ).each do |code|
    get code, to: "static_pages#error", code: code
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flashcards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>
  <body>
    <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation" data-controller="main-nav">
      <div class="navbar-brand">
        <%= link_to(decks_path, class: "navbar-item") do %>
          <%= image_tag("logo_120.png", class: "site-logo-image") %>
          <span class="navbar-title has-text-weight-semibold">Flashcards</span>
        <% end %>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-main-nav-target="mainNavBurger" data-action="click->main-nav#toggle">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div class="navbar-menu main-nav-menu" data-main-nav-target="mainNavMenu">
        <div class="navbar-start main-nav-items">
          <%= link_to(decks_path, class: "navbar-item has-text-weight-bold") do %>
            <span class="icon is-small">
              <i class="fas fa-folder-open"></i>
            </span>
            <span>All Decks</span>
          <% end %>
          <%= link_to(cards_path, class: "navbar-item has-text-weight-bold") do %>
            <span class="icon is-small">
              <i class="fas fa-sticky-note"></i>
            </span>
            <span>All Cards</span>
          <% end %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link has-text-weight-bold">
              <span class="icon is-small">
                <i class="fas fa-plus"></i>
              </span>
              <span>New</span>
            </a>

            <div class="navbar-dropdown is-boxed">
              <%= link_to("New Card", new_card_path, class: "navbar-item") %>
              <%= link_to("New Deck", new_deck_path, class: "navbar-item") %>
            </div>
          </div>
        </div>

        <div class="navbar-end"></div>
          <% if @current_user.present? %>
            <%= link_to('Log out', logout_path, method: :delete, class: "navbar-item button is-small is-danger is-outlined logout-button") %>
          <% else %>
            <%= link_to('Log in', login_path, class: "navbar-item button is-small is-success login-button") %>
          <% end %>
      </div>
    </nav>

    <div class="page-container">
      <% if flash[:alert] %>
        <div class="flash notification is-danger" data-controller="flash">
          <button class="delete" data-action="click->flash#close"></button>
          <p class="notice"><%= flash[:alert] %></p>
        </div>
      <% elsif flash[:notice] %>
        <div class="flash notification is-warning" data-controller="flash">
          <button class="delete" data-action="click->flash#close"></button>
          <p class="notice"><%= flash[:notice] %></p>
        </div>
      <% elsif flash[:success] %>
        <div class="flash notification is-success" data-controller="flash">
          <button class="delete" data-action="click->flash#close"></button>
          <p class="notice"><%= flash[:success] %></p>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <% if ENV['SERVICE_WORKER_ENABLED'] %>
      <script>
        if ('serviceWorker' in navigator) {
          window.addEventListener('load', () => {
            navigator.serviceWorker.register('/service-worker.js');
          });
        }
      </script>
    <% end %>
  </body>
</html>